import type { AppProps } from 'next/app'
import Head from 'next/head'
import React from 'react'
import '../styles/globals.css'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div>
      <Head>
        <title>{"Eve's Fermentation Lab"}</title>
        <meta name="Eve's Fermentation Lab" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Component {...pageProps} />
    </div>
  )
}

export default MyApp
