import type { NextPage } from 'next'
import Head from 'next/head'
import { Gallery } from '../components/Gallery'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{"Eve's Fermentation Lab"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen bg-primary'>
        <div className='flex h-screen'>
          <div className='w-[50vw] h-screen'>
            <h1>{"Eve's Fermentation Lab"}</h1>
          </div>
          <div className='w-[50vw] h-screen flex overflow-hidden bg-primary'>
            <div className='w-[50vw] h-screen flexrelative flex justify-center items-center overflow-hidden'>
              <Gallery 
                images={[
                  "/assets/img/IMG_6786.jpg",
                  "/assets/img/IMG_6788.jpg",
                  "/assets/img/IMG_6797.jpg",
                  "/assets/img/IMG_6818.jpg",
                ]}
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
